---
parent: "example_v1_hotels"
name: "ExampleV1HotelsGetQueryParamNullValueSize"
description: "The list is paginated. You can provide a page number (default 0) and\
  \ a page size (default 100)"
type: "SUITE"
endpoint: "/example/v1/hotels"
method: "GET"
auth: "Default"
headers:
- "Accept: application/json"
- "Content-Type: application/json"
testCases: []
assertions:
- "@StatusCode != 200"
- "@StatusCode != 401"
- "@StatusCode != 404"
- "@StatusCode != 500"
tags:
- "V1"
authors:
- "FX Bot"
category: "Negative"
severity: "Critical"
inactive: false
policies: null
